name: Purge Caddy Cache

on:
  workflow_dispatch:

env:
  GO_VERSION: '1.22'  # Match your main workflow

jobs:
  purge-cache:
    runs-on: ubuntu-latest
    permissions:
      actions: write  # Required for cache deletion
      contents: read  # Required for checkout
    steps:
      - name: Check out code
        uses: actions/checkout@v4

      - name: Get cache key
        id: get-key
        run: |
          # Generate the same cache key format as the build workflow
          KEY="${{ runner.os }}-caddy-${{ hashFiles('**/go.sum') || 'no-deps' }}-${GO_VERSION}-2.9"
          echo "cache_key=$KEY" >> $GITHUB_OUTPUT

      - name: Delete cache
        env:
          GH_TOKEN: ${{ github.token }}
        run: |
          # Get the cache ID for the specific key
          CACHE_ID=$(gh api -H "Accept: application/vnd.github+json" \
            "/repos/${{ github.repository }}/actions/caches" \
            --jq ".actions_caches[] | select(.key == \"${{ steps.get-key.outputs.cache_key }}\") | .id")
          
          if [ -n "$CACHE_ID" ]; then
            echo "Found cache with ID: $CACHE_ID"
            echo "Deleting cache with key: ${{ steps.get-key.outputs.cache_key }}"
            gh api --method DELETE \
              -H "Accept: application/vnd.github+json" \
              "/repos/${{ github.repository }}/actions/caches/$CACHE_ID"
            echo "Cache deleted successfully"
          else
            echo "No cache found with key: ${{ steps.get-key.outputs.cache_key }}"
            exit 0  # Don't fail if cache doesn't exist
          fi